### ISSUE TITLE
A uncaught exception occured: Error: Invalid I2C address. Valid addresses are 0 through 0x7f.

### ISSUE THREAD

**Issue by Holzknoten** [mwittig/pimatic-johnny-five#46]
[Update because wrong witten of **MCP23017**, but same Problem]
Hi,

i realy like johnny five. thanks for that plugin.
I know that have to be a bug in Pimatic, but mabee someone can help me.

I go the following error message when using a second **MCP23017** in config,json of pimatic.
A uncaught exception occured: Error: Invalid I2C address. Valid addresses are 0 through 0x7f.

```
  "boards": [
    {
      "id": "1",
      "boardType": "raspi-io"
    },
    {
      "id": "2",
      "boardType": "expander",
      "port": "1",
      "controller": "MCP23017"
    },
    {
      "id": "3",
      "boardType": "expander",
      "port": "1",
      "controller": "MCP23017",
      **"address": "0x21"**
    }
```
I got the tip to type in the dezimal.
So heximal 0x21 will be dezimal 33.

I try this different inputs. normaly it have to be a Sring and not a integer.
But i give it a try.
“address”: “33"
“address”: 33
"address”: "0x21"
“address”: 0x21

Doesn’t work for me. any tip or suggestion?

**Comment by mwittig** [comment]
I think the problem is the typo in the controller id.

Replace `MPC23017` with `MCP23017`

**Comment by Holzknoten** [comment]
thanks for your answer.
yes inside this post i wrote it not correct. MCP23017

inside my config.json i wrote it in the correct way.
The first MCP23017 get the default adress 0x20 automatically.
My problem is the second MCP23017 needs the adress value.

```
sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: 20 21 -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

inside my config.json:

```
 {
      "boards": [
        {
          "id": "1",
          "boardType": "raspi-io"
        },
        {
          "id": "2",
          "boardType": "expander",
          "port": "1",
          "controller": "MCP23017"
        },
        {
          "id": "3",
          "boardType": "expander",
          "port": "1",
          "controller": "MCP23017",
          "address": "0x21"
        }
      ],
      "plugin": "johnny-five",
      "active": true
    },
```

pimatic start crash and stop working.

```
20:41:00.697 [pimatic] A uncaught exception occured: Error: Invalid I2C address 0x21. Valid addresses are 0 through 0x7f.
20:41:00.697 [pimatic]>    at checkAddress (../index.js:32:11)
20:41:00.697 [pimatic]>    at I2C.writeSync (../index.js:293:5)
20:41:00.697 [pimatic]>    at Raspi.i2cWrite (../index.js:538:17)
20:41:00.697 [pimatic]>    at Expander.Controllers.MCP23017.initialize.value (/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/johnny-five/lib/expander.js:57:17)
20:41:00.697 [pimatic]>    at new Expander (/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/johnny-five/lib/expander.js:1868:10)
20:41:00.697 [pimatic]>    at BoardWrapper.<anonymous> (/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/board-manager.coffee:38:20)
20:41:00.697 [pimatic]>    at BoardWrapper.g (events.js:260:16)
20:41:00.697 [pimatic]>    at emitOne (events.js:82:20)
20:41:00.697 [pimatic]>    at BoardWrapper.emit (events.js:169:7)
20:41:00.697 [pimatic]>    at BoardWrapper.finalizeAndBroadcast (/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/johnny-five/lib/board.js:457:12)
20:41:00.697 [pimatic]>    at BoardWrapper.<anonymous> (/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/johnny-five/lib/board.js:322:32)
20:41:00.697 [pimatic]>    at Raspi.g (events.js:260:16)
20:41:00.697 [pimatic]>    at emitNone (events.js:67:13)
20:41:00.697 [pimatic]>    at Raspi.emit (events.js:166:7)
20:41:00.697 [pimatic]>    at ../index.js:319:12
20:41:00.697 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
```

**Comment by mwittig** [comment]
pimatic-johnny-five@0.9.5

**Comment by Holzknoten** [comment]
Update is done.
Log:
Updates
pimatic is up to date.

All plugins are up to date.

```
> raspi-wiringpi@1.0.6 install /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi/node_modules/raspi-wiringpi
> sh install-wiringpi.sh
Wiring Pi is already installed, skipping
> raspi-pwm@3.1.0 install /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-pwm
> node-gyp rebuild
make: Entering directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-pwm/build'
CXX(target) Release/obj.target/addon/src/addon.o
CXX(target) Release/obj.target/addon/src/init.o
CXX(target) Release/obj.target/addon/src/write.o
SOLINK_MODULE(target) Release/obj.target/addon.node
COPY Release/addon.node
make: Leaving directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-pwm/build'
> raspi@2.1.0 install /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi
> node-gyp rebuild
make: Entering directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi/build'
CXX(target) Release/obj.target/addon/src/addon.o
CXX(target) Release/obj.target/addon/src/init.o
SOLINK_MODULE(target) Release/obj.target/addon.node
COPY Release/addon.node
make: Leaving directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi/build'
> raspi-gpio@2.3.0 install /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-gpio
> node-gyp rebuild
make: Entering directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-gpio/build'
CXX(target) Release/obj.target/addon/src/addon.o
CXX(target) Release/obj.target/addon/src/init.o
CXX(target) Release/obj.target/addon/src/write.o
CXX(target) Release/obj.target/addon/src/read.o
SOLINK_MODULE(target) Release/obj.target/addon.node
COPY Release/addon.node
make: Leaving directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-gpio/build'
> i2c-bus@1.1.2 install /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-i2c/node_modules/i2c-bus
> node-gyp rebuild
make: Entering directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-i2c/node_modules/i2c-bus/build'
CXX(target) Release/obj.target/i2c/src/i2c.o
SOLINK_MODULE(target) Release/obj.target/i2c.node
COPY Release/i2c.node
make: Leaving directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-i2c/node_modules/i2c-bus/build'
> serialport@4.0.5 install /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/johnny-five/node_modules/serialport
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.5/serialport-v4.0.5-node-v46-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.5 and node@4.4.5 (node-v46 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/johnny-five/node_modules/serialport/build'
CXX(target) Release/obj.target/serialport/src/serialport.o
CXX(target) Release/obj.target/serialport/src/serialport_unix.o
CXX(target) Release/obj.target/serialport/src/serialport_poller.o
SOLINK_MODULE(target) Release/obj.target/serialport.node
COPY Release/serialport.node
make: Leaving directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/johnny-five/node_modules/serialport/build'
> serialport@4.0.5 install /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-serial/node_modules/serialport
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.5/serialport-v4.0.5-node-v46-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.5 and node@4.4.5 (node-v46 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-serial/node_modules/serialport/build'
CXX(target) Release/obj.target/serialport/src/serialport.o
CXX(target) Release/obj.target/serialport/src/serialport_unix.o
CXX(target) Release/obj.target/serialport/src/serialport_poller.o
SOLINK_MODULE(target) Release/obj.target/serialport.node
COPY Release/serialport.node
make: Leaving directory '/home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-serial/node_modules/serialport/build'
> raspi-i2c@3.1.1 postinstall /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-i2c
> echo "Enabling I2C at boot time, you may be asked for your password" && sudo env "PATH=$PATH" script/enable_i2c.js
Enabling I2C at boot time, you may be asked for your password
Checking if I2C is enabled at boot time
I2C is already enabled at boot time
> raspi-serial@2.0.0 postinstall /home/redsean/pimatic-app/node_modules/pimatic-johnny-five/node_modules/raspi-io/node_modules/raspi-serial
> echo "Disabling serial port login at boot time, you may be asked for your password" && sudo env "PATH=$PATH" script/enable_serial.js
Disabling serial port login at boot time, you may be asked for your password
Checking if serial port login is enabled
Serial port login does not appear to be enabled, skipping
pimatic-johnny-five@0.9.5 node_modules/pimatic-johnny-five
├── oled-font-5x7@1.0.0
├── pimatic-plugin-commons@0.9.3
├── oled-js@4.0.2
├── etherport-client@0.1.2 (debug@2.2.0)
├── etherport@0.1.4 (es6-shim@0.35.1)
├── particle-io@0.14.0 (es6-shim@0.35.1, array-includes@3.0.2)
├── johnny-five@0.10.3 (lodash.debounce@4.0.8, lodash.clonedeep@4.5.0, ease-component@1.0.0, browser-serialport@2.0.3, color-convert@1.2.2, temporal@0.5.0, nanotimer@0.3.10, chalk@1.1.3, firmata@0.14.1, es6-shim@0.35.1, serialport@4.0.5)
└── raspi-io@6.1.1 (raspi-board@4.0.0, raspi-led@1.5.1, raspi-pwm@3.1.0, raspi@2.1.0, raspi-gpio@2.3.0, raspi-i2c@3.1.1, raspi-serial@2.0.0)
Updates were successful. Please restart pimatic.

Restart pimatic
05:3019:1509:0019:1500:0000:0000:0000:00
```

First test edit change address:0x21 to 33
Log: xerror [pimatic]: Invalid config of pimatic-johnny-five: Property "#/boards/1/address" Should have type string, was: integer in /boards/1/address

More tests will follow today...

**Comment by mwittig** [comment]
> Log: xerror [pimatic]: Invalid config of pimatic-johnny-five: Property "#/boards/1/address" Should have type 

Address should be provided as string, e.g. "address": "0x21" as using hex number in the config is not supported (not supported by JSON). 

> More tests will follow today...

Great. Please keep me posted.

**Comment by Holzknoten** [comment]
Inside pimatic config i type in 0x21 and pimatic change it to 33, in the fly

i stop pimatic, edit directly the config.json with 0x21 and start pimatic.

Now it is Working. Thanks for the update.

**Comment by mwittig** [comment]
That's great. Thanks for reporting
