### ISSUE TITLE
Exception raised using expander board with raspi-io

### ISSUE THREAD

**Issue by mwittig** [mwittig/pimatic-johnny-five#54]
Seems like the recent version of johnny-five changed the initialization order for boards.

```
15:19:10.821 [pimatic] error: A uncaught exception occured: TypeError: Cannot read property 'i2cConfig' of null
15:19:10.821 [pimatic] error:>    at Expander.Controllers.MCP23017.initialize.value (/home/pi/pimatic-dev/node_modules/pimatic-johnny-five/node_modules/johnny-five/lib/expander.js:56:16)
15:19:10.821 [pimatic] error:>    at new Expander (/home/pi/pimatic-dev/node_modules/pimatic-johnny-five/node_modules/johnny-five/lib/expander.js:1868:10)
15:19:10.821 [pimatic] error:>    at BoardWrapper.<anonymous> (/home/pi/pimatic-dev/node_modules/pimatic-johnny-five/board-manager.coffee:39:20)
15:19:10.821 [pimatic] error:>    at BoardWrapper.g (events.js:260:16)
15:19:10.821 [pimatic] error:>    at emitOne (events.js:82:20)
15:19:10.821 [pimatic] error:>    at BoardWrapper.emit (events.js:169:7)
15:19:10.821 [pimatic] error:>    at BoardWrapper.finalizeAndBroadcast (/home/pi/pimatic-dev/node_modules/pimatic-johnny-five/node_modules/johnny-five/lib/board.js:457:12)
15:19:10.821 [pimatic] error:>    at BoardWrapper.<anonymous> (/home/pi/pimatic-dev/node_modules/pimatic-johnny-five/node_modules/johnny-five/lib/board.js:322:32)
15:19:10.821 [pimatic] error:>    at Raspi.g (events.js:260:16)
15:19:10.821 [pimatic] error:>    at emitNone (events.js:67:13)
15:19:10.821 [pimatic] error:>    at Raspi.emit (events.js:166:7)
15:19:10.821 [pimatic] error:>    at /home/pi/pimatic-dev/node_modules/pimatic-johnny-five/node_modules/raspi-io/index.js:319:12
15:19:10.821 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!

**Comment by mwittig** [comment]
Fix released with pimatic-johnny-five@0.9.7
